services:
  # web:
  #   build: aspnetapp
  #   ports:
  #     - 80:8080
  #   volumes:
  #     - ./aspnetapp:/src

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "8081:80"

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
