services:
  redmine:
    image: redmine
    restart: unless-stopped
    ports:
      - 8000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "8001:80"

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
